import { sql } from "drizzle-orm";
import {
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import type { AdapterAccountType } from "next-auth/adapters";

// ─── Custom types ───────────────────────────────────────────────────

// pgvector — embedding column with HNSW index support
const vector = customType<{ data: number[]; driverData: string }>({
  dataType() {
    return "vector(1536)";
  },
  toDriver(value: number[]): string {
    return JSON.stringify(value);
  },
  fromDriver(value: string): number[] {
    return JSON.parse(value) as number[];
  },
});

// tsvector — generated full-text search column
const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector";
  },
});

// ─── Enums ──────────────────────────────────────────────────────────

export const entityTypeEnum = pgEnum("entity_type", [
  "product",
  "tech",
  "vendor",
  "decision",
  "pattern",
  "incident",
  "lesson",
  "goal",
  "person",
  "roadmap_item",
  "rule",
  "skill",
]);

export const edgeRelationEnum = pgEnum("edge_relation", [
  "uses",
  "hosted_on",
  "applies_to",
  "supersedes",
  "led_to",
  "shares_pattern",
  "mentions",
  "defined_by",
  "blocks",
  "depends_on",
]);

export const goalStatusEnum = pgEnum("goal_status", [
  "active",
  "completed",
  "abandoned",
  "blocked",
]);

export const eventTypeEnum = pgEnum("event_type", [
  "entity_created",
  "entity_updated",
  "entity_deleted",
  "edge_created",
  "edge_deleted",
  "search_query",
  "graph_query",
  "skill_promotion_proposed",
  "decay_flag_raised",
  "agent_invocation",
]);

export const playbookTriggerEnum = pgEnum("playbook_trigger", [
  "project_created",
  "project_updated",
  "scope_changed",
  "tech_stack_changed",
  "significant_change",
  "entity_added",
  "manual",
]);

export const invocationStatusEnum = pgEnum("invocation_status", [
  "pending",
  "in_progress",
  "completed",
  "abandoned",
]);

export const invocationActionStatusEnum = pgEnum("invocation_action_status", [
  "pending",
  "completed",
  "rejected",
  "failed",
]);

// ─── Brain: entities (graph nodes) ─────────────────────────────────

export const entities = pgTable(
  "entities",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    slug: varchar("slug", { length: 128 }).notNull(),
    type: entityTypeEnum("type").notNull(),
    name: text("name").notNull(),
    description: text("description").notNull().default(""),
    frontmatter: jsonb("frontmatter").$type<Record<string, unknown>>().default({}).notNull(),
    sourcePath: text("source_path"), // path to the source markdown file
    embedding: vector("embedding"), // 1536-dim for text-embedding-3-small
    searchVector: tsvector("search_vector"), // generated by trigger from name + description
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    lastValidatedAt: timestamp("last_validated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  },
  (t) => [
    uniqueIndex("entities_slug_idx").on(t.slug),
    index("entities_type_idx").on(t.type),
    index("entities_last_validated_idx").on(t.lastValidatedAt),
    // pgvector HNSW index — must be created via raw SQL in migration
    // tsvector GIN index — must be created via raw SQL in migration
  ],
);

// ─── Brain: edges (typed relationships) ────────────────────────────

export const edges = pgTable(
  "edges",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fromEntityId: uuid("from_entity_id")
      .notNull()
      .references(() => entities.id, { onDelete: "cascade" }),
    toEntityId: uuid("to_entity_id")
      .notNull()
      .references(() => entities.id, { onDelete: "cascade" }),
    relation: edgeRelationEnum("relation").notNull(),
    declaredByEntityId: uuid("declared_by_entity_id").references(() => entities.id, {
      onDelete: "cascade",
    }),
    context: text("context"), // snippet of markdown around the declaration
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("edges_unique_idx").on(t.fromEntityId, t.toEntityId, t.relation),
    index("edges_from_idx").on(t.fromEntityId),
    index("edges_to_idx").on(t.toEntityId),
    index("edges_relation_idx").on(t.relation),
  ],
);

// ─── Brain: goals (durable objectives) ─────────────────────────────

export const goals = pgTable(
  "goals",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    targetDate: timestamp("target_date", { withTimezone: true }),
    status: goalStatusEnum("status").notNull().default("active"),
    relatedEntityIds: uuid("related_entity_ids").array().notNull().default(sql`'{}'::uuid[]`),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
  },
  (t) => [
    index("goals_status_idx").on(t.status),
    index("goals_target_date_idx").on(t.targetDate),
  ],
);

// ─── Brain: maintenance_runs (cron-fire log) ───────────────────────
// Every invocation of `runMaintenance(kind)` writes a row. Lets us show
// "Decay: last ran 6h ago, 0 findings" even when no goal was created —
// closes the visibility gap Sam hit on first cron night ("did the cron
// fire?" had no answer because zero-finding runs produced nothing).

export const maintenanceKindEnum = pgEnum("maintenance_kind", [
  "decay",
  "dedupe",
  "audit-edges",
  "contradictions",
]);

export const maintenanceRuns = pgTable(
  "maintenance_runs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    kind: maintenanceKindEnum("kind").notNull(),
    ranAt: timestamp("ran_at", { withTimezone: true }).defaultNow().notNull(),
    findingsCount: integer("findings_count").notNull(),
    threshold: integer("threshold").notNull(),
    exceededThreshold: boolean("exceeded_threshold").notNull(),
    /** "created" | "updated" | "completed" | "noop" — mirrors upsertSystemGoal output. */
    goalAction: text("goal_action").notNull(),
    goalId: uuid("goal_id"),
    durationMs: integer("duration_ms").notNull().default(0),
  },
  (t) => [
    index("maintenance_runs_kind_idx").on(t.kind),
    index("maintenance_runs_ran_at_idx").on(t.ranAt),
  ],
);

// ─── Brain: scratchpad (agent ephemeral memory) ────────────────────

export const scratchpad = pgTable(
  "scratchpad",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    agentId: varchar("agent_id", { length: 128 }).notNull(),
    sessionId: varchar("session_id", { length: 128 }).notNull(),
    key: varchar("key", { length: 256 }).notNull(),
    value: jsonb("value").$type<unknown>().notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("scratchpad_lookup_idx").on(t.agentId, t.sessionId, t.key),
    index("scratchpad_expires_idx").on(t.expiresAt),
  ],
);

// ─── Brain: events (audit log + auto-detector input) ──────────────

export const events = pgTable(
  "events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    type: eventTypeEnum("type").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
    entityIds: uuid("entity_ids").array().notNull().default(sql`'{}'::uuid[]`),
    actorId: varchar("actor_id", { length: 128 }), // user id, agent id, or "system"
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("events_type_idx").on(t.type),
    index("events_created_at_idx").on(t.createdAt),
  ],
);

// ─── Brain: playbooks (recurring instructions / standing rules) ──

export const playbooks = pgTable(
  "playbooks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    slug: varchar("slug", { length: 128 }).notNull(),
    name: text("name").notNull(),
    description: text("description").notNull().default(""),
    trigger: playbookTriggerEnum("trigger").notNull(),
    // Optional structured filter — only fire playbook when context matches.
    // e.g. { entityType: "product", clientWork: false } restricts to non-client products.
    filter: jsonb("filter").$type<Record<string, unknown>>().default({}).notNull(),
    // Ordered free-text instructions for the agent (Claude / Cursor / etc.) to follow
    // when this playbook fires. Each step is one action.
    actions: text("actions").array().notNull(),
    // Optional list of entity slugs this playbook applies to. Empty array = all matching.
    // e.g. ["kodori", "roushi"] limits the playbook to those two products.
    appliesToSlugs: text("applies_to_slugs").array().notNull().default(sql`'{}'::text[]`),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("playbooks_slug_idx").on(t.slug),
    index("playbooks_trigger_idx").on(t.trigger),
    index("playbooks_active_idx").on(t.active),
  ],
);

// ─── Brain: playbook invocations + per-action approval state ─────

export const playbookInvocations = pgTable(
  "playbook_invocations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    playbookId: uuid("playbook_id")
      .notNull()
      .references(() => playbooks.id, { onDelete: "cascade" }),
    // Snapshot of the trigger event that fired this invocation.
    eventTrigger: playbookTriggerEnum("event_trigger").notNull(),
    eventContext: jsonb("event_context").$type<Record<string, unknown>>().default({}).notNull(),
    // Optional — the entity the event was about (e.g. the project that was created).
    entityId: uuid("entity_id").references(() => entities.id, { onDelete: "set null" }),
    status: invocationStatusEnum("status").notNull().default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("playbook_invocations_playbook_idx").on(t.playbookId),
    index("playbook_invocations_status_idx").on(t.status),
    index("playbook_invocations_created_idx").on(t.createdAt),
  ],
);

export const invocationActions = pgTable(
  "invocation_actions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    invocationId: uuid("invocation_id")
      .notNull()
      .references(() => playbookInvocations.id, { onDelete: "cascade" }),
    actionIndex: integer("action_index").notNull(),
    actionText: text("action_text").notNull(),
    status: invocationActionStatusEnum("status").notNull().default("pending"),
    notes: text("notes"),
    /** Who/what marked this action complete: "manual" (a human) or an agent id. */
    completedBy: varchar("completed_by", { length: 128 }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("invocation_actions_unique_idx").on(t.invocationId, t.actionIndex),
    index("invocation_actions_status_idx").on(t.status),
  ],
);

// ─── Auth.js v5 required tables ────────────────────────────────────

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name"),
  email: text("email").notNull(),
  emailVerified: timestamp("email_verified", { mode: "date", withTimezone: true }),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const accounts = pgTable(
  "accounts",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccountType>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] })],
);

export const sessions = pgTable("sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date", withTimezone: true }).notNull(),
});

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date", withTimezone: true }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

// ─── Type exports ─────────────────────────────────────────────────

export type Entity = typeof entities.$inferSelect;
export type NewEntity = typeof entities.$inferInsert;
export type Edge = typeof edges.$inferSelect;
export type NewEdge = typeof edges.$inferInsert;
export type Goal = typeof goals.$inferSelect;
export type NewGoal = typeof goals.$inferInsert;
export type ScratchpadEntry = typeof scratchpad.$inferSelect;
export type NewScratchpadEntry = typeof scratchpad.$inferInsert;
export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;
export type Playbook = typeof playbooks.$inferSelect;
export type NewPlaybook = typeof playbooks.$inferInsert;
export type PlaybookInvocation = typeof playbookInvocations.$inferSelect;
export type NewPlaybookInvocation = typeof playbookInvocations.$inferInsert;
export type InvocationAction = typeof invocationActions.$inferSelect;
export type NewInvocationAction = typeof invocationActions.$inferInsert;
